tei/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'tei'
urlpatterns = [
    path('iiif/presentation/<int:pk>/', views.IIIFPresentationPluginModelDetailView.as_view(), name='iiif-presentation-detail'),
]

tei/models.py
# -*- coding: utf-8 -*-
import urllib.parse
from django.db import models
from django.urls import reverse
from cms.models import CMSPlugin
from pathlib import Path
import urllib.parse

from model_utils.models import TimeStampedModel


class TEIPublisher(TimeStampedModel):
    name = models.CharField(max_length=255, help_text="A unique name for this instance of TEI Publisher.")
    endpoint = models.CharField(max_length=1023, blank=True, default="", help_text="A URL to the endpoint of this TEI Publisher instance.")
    
    class Meta:
        verbose_name_plural = "TEI Publisher Instances"

    def __str__(self):
        return self.name or self.endpoint
    

class IIIFServer(TimeStampedModel):
    name = models.CharField(max_length=255, help_text="A unique name for this instance of this IIIF Server.")
    uri = models.CharField(max_length=1023, blank=False, help_text="A URL to the endpoint of this IIIF Server.")
    
    class Meta:
        verbose_name_plural = "IIIF Servers"
        verbose_name = "IIIF Server"

    def __str__(self):
        return self.name or self.uri
    
    def info_uri(self, identifier):
        identifier_string = str(identifier)
        # Check if we can escape this string
        if "%" not in identifier_string:
            identifier_string = urllib.parse.quote_plus(identifier_string)
        return Path(self.uri)/identifier_string/"info.json"


class TEIDoc(TimeStampedModel):
    name = models.CharField(max_length=255, help_text="A name/title for this TEI document.")
    publisher = models.ForeignKey(TEIPublisher, verbose_name="TEI Publisher Instance", on_delete=models.CASCADE, help_text="The instance of TEI Publisher hosting this document.")
    iiif = models.ForeignKey(IIIFServer, verbose_name="IIIF Server", default=None, blank=True, null=True, on_delete=models.SET_DEFAULT, help_text="A IIIF server hosting images referenced in this document.")
    path = models.CharField(max_length=1023, help_text="The path to the TEI XML file on the TEI Publisher instance.")
    odd = models.CharField(max_length=255, verbose_name="ODD", help_text="The ODD to use for this TEI document. Must be on the TEI Publisher instance.")
    template = models.CharField(max_length=255, blank=True, default="", help_text="The Django template to display this document. Template must be in Django instance. Default: tei/teidoc_detail.html")
    
    class Meta:
        verbose_name = "TEI Doc"
        verbose_name_plural = "TEI Docs"

    def __str__(self):
        return self.name or self.xml

    def get_absolute_url(self):
        return reverse('tei:TEIDoc_detail', kwargs=dict(pk=self.pk))

    def url_transformed(self, format):
        format = format.lower()
        if format not in ["pdf", "html", "epub"]:
            raise Exception("format must be one of pdf, html or epub")

        path_encoded = urllib.parse.quote_plus(self.path)

        # The API requires the extensino for the ODD
        odd = self.odd
        if not odd.endswith(".odd"):
            odd += ".odd"
        
        url = f"{self.publisher.endpoint}/api/document/{path_encoded}/{format}?odd={odd}&wc=true"
        return url
    
    def url_pdf(self):
        return self.url_transformed("pdf")

    def url_epub(self):
        return self.url_transformed("epub")

    def url_html(self):
        return self.url_transformed("html")


class TEIDocPluginModel(CMSPlugin):
    doc = models.ForeignKey(TEIDoc, on_delete=models.CASCADE)

    def __str__(self):
        return self.doc.name


class IIIFImagePluginModel(CMSPlugin):
    identifier = models.CharField(max_length=255, help_text="The identifier of this image on the IIIF server.")
    iiif = models.ForeignKey(IIIFServer, verbose_name="IIIF Server", default=None, blank=True, null=True, on_delete=models.SET_DEFAULT, help_text="The IIIF server hosting this image.")

    def __str__(self):
        return self.identifier

    def info_uri(self):
        return self.iiif.info_uri( self.identifier )


class IIIFPresentationPluginModel(CMSPlugin):
    manifest_uri = models.CharField(max_length=1023, help_text="The URI to the manifest for this IIIF presentation.")
    width = models.CharField(max_length=31, default="100%", help_text="The width of the presentation when displayed.")
    height = models.CharField(max_length=31, default="500px", help_text="The height of the presentation when displayed.")

    def __str__(self):
        return self.manifest_uri

tei/test_utils/test_app/models.py
from django.db import models

# Put your test models here

tei/views.py
# -*- coding: utf-8 -*-
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
    ListView
)

from .models import (
	TEIDoc,
	TEIPublisher,
    IIIFPresentationPluginModel,
)


class TEIDocCreateView(CreateView):
    model = TEIDoc


class TEIDocDeleteView(DeleteView):
    model = TEIDoc


class TEIDocDetailView(DetailView):
    model = TEIDoc

    def get_template_names(self):
        """ First tries the template name from the object. """
        self.object = self.get_object()
        if self.object.template:
            return [self.object.template]
        return super().get_template_names()


class TEIDocUpdateView(UpdateView):

    model = TEIDoc


class TEIDocListView(ListView):
    model = TEIDoc
    paginate_by = "50"


class TEIPublisherCreateView(CreateView):
    model = TEIPublisher


class TEIPublisherDeleteView(DeleteView):
    model = TEIPublisher


class TEIPublisherDetailView(DetailView):
    model = TEIPublisher


class TEIPublisherUpdateView(UpdateView):
    model = TEIPublisher


class TEIPublisherListView(ListView):
    model = TEIPublisher

class IIIFPresentationPluginModelDetailView(DetailView):
    model = IIIFPresentationPluginModel
    template_name = "tei/iiif-presentation-detail.html"
    context_object_name = "instance"

tei/templates/tei/base.html
{% comment %}
As the developer of this package, don't place anything here if you can help it
since this allows developers to have interoperability between your template
structure and their own.

Example: Developer melding the 2SoD pattern to fit inside with another pattern::

    {% extends "base.html" %}
    {% load static %}

    <!-- Their site uses old school block layout -->
    {% block extra_js %}

        <!-- Your package using 2SoD block layout -->
        {% block javascript %}
            <script src="{% static 'js/ninja.js' %}" type="text/javascript"></script>
        {% endblock javascript %}

    {% endblock extra_js %}
{% endcomment %}

tei/templates/tei/iiif-image.html
{% load sekizai_tags %}

<div id="iiifimage{{instance.id}}" style="width: 100%76; height: 600px;"></div>

{% addtoblock "js" %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/openseadragon/2.4.2/openseadragon.min.js"></script>
{% endaddtoblock %}

{% addtoblock "js" %}
<script type="text/javascript">
    OpenSeadragon({
        id:            "iiifimage{{instance.id}}",
        prefixUrl:     "https://cdnjs.cloudflare.com/ajax/libs/openseadragon/2.4.2/images/",
        sequenceMode:  false,
        tileSources:   ["{{ instance.info_uri }}"]
    });

</script>
{% endaddtoblock %}

tei/templates/tei/iiif-presentation-detail.html
<html>
    <div id="mirador{{instance.id}}" style="width: 600px; height: 600px;"></div>

    <script src="https://cdn.jsdelivr.net/npm/mirador@3.2.0/dist/mirador.min.js" integrity="sha256-e11UQD1U7ifc8OK9X0rVMshTXSKl7MafRxi3PTwXDHs=" crossorigin="anonymous"></script>

    <script type="text/javascript">
        var mirador = Mirador.viewer({
            "id": "mirador{{instance.id}}",
            "manifests": {
                "{{instance.manifest_uri}}": {
                "provider": "University of Melbourne"
                }
            },
            "windows": [
                {
                "loadedManifest": "{{instance.manifest_uri}}",
                "canvasIndex": 1,
                "thumbnailNavigationPosition": 'far-bottom'
                }
            ]
        });
    </script>
</html>

tei/templates/tei/iiif-presentation.html
<iframe src='{% url "tei:iiif-presentation-detail" pk=instance.id %}' style="{% if instance.width %}width: {{ instance.width }};{%endif%} {% if instance.height %}height: {{ instance.height }};{%endif%}">
    {{ instance }}
</iframe>

tei/templates/tei/teidoc_complicated.html
{% extends "tei/teidoc_detail.html" %}


{% block content %}

<h1>{{ teidoc.name }}</h1>

<pb-page endpoint="{{ teidoc.publisher.endpoint }}">
    <pb-document id="document1" path="{{ teidoc.path }}" odd="{{ teidoc.odd }}" view="page"></pb-document>

    <main>
      <pb-view id="view1" src="document1"></pb-view>
    </main>
</pb-page>

{% endblock content %}

tei/templates/tei/teidoc_detail.html
{% extends "base.html" %}

{% block head %}
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.4.3/webcomponents-loader.js"></script>
<script type="module" src="https://unpkg.com/@teipublisher/pb-components@latest/dist/pb-components-bundle.js"></script>

{% block teihead %}
{% endblock teihead %}

{% endblock head %}


{% block content %}
<div class=container>


<pb-page endpoint="{{ teidoc.publisher.endpoint }}">
    <pb-document id="document1" path="{{ teidoc.path }}" odd="{{ teidoc.odd }}" view="page"></pb-document>

    <main>
      <pb-view id="view1" src="document1"></pb-view>
    </main>
</pb-page>

</div>
{% endblock content %}

tei/templates/tei/teidoc_facsimiles.html
{% extends "tei/teidoc_detail.html" %}


{% block content %}

<pb-page endpoint="{{ teidoc.publisher.endpoint }}">
    <pb-document id="document1" path="{{ teidoc.path }}" odd="{{ teidoc.odd }}"></pb-document>
    <main>
        <pb-facsimile base-uri="{{ teidoc.iiif.uri }}" default-zoom-level="0" show-navigator="show-navigator" show-navigation-control="show-navigation-control">
        </pb-facsimile>
        <pb-view id="view1" src="document1" view="page" xpath="//text[@type='source']" append-footnotes>
        </pb-view>

    </main>
    <footer>
        <!-- Navigate to next page -->
        <pb-navigation direction="forward" keyboard="right">
            <paper-button>
                <iron-icon icon="icons:chevron-right"></iron-icon>
            </paper-button>
        </pb-navigation>
        <!-- Navigate to previous page -->
        <pb-navigation direction="backward" keyboard="left">
            <paper-button>
                <iron-icon icon="icons:chevron-left"></iron-icon>
            </paper-button>
        </pb-navigation>
    </footer>
</pb-page>

{% endblock content %}


{% block teihead %}
<style>
    
main {
    display: flex;
    flex-direction: row;
    justify-content: flex-start;
}

footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #f0f0f0;
}

pb-navigation[disabled] {
    display: block;
    visibility: hidden;
}

pb-navigation[direction="forward"] {
    float: right;
}

#view1 {
    flex: 3;
    margin-left: 20px;
    font-size: 20px;
    line-height: 1.42857143;
}

pb-facsimile {
    flex: 2;
    max-width: 50vw;
    --pb-facsimile-height: calc(100vh - 60px);
    margin-right: 20px;
}


</style>
{% endblock %}

tei/templates/tei/teidoc_list.html
{% extends "base.html" %}

{% block content %}

<div class=container>


<ul>
{% for doc in page_obj %}
    <li><a href='{{ doc.get_absolute_url }}'>{{ doc }}</a></li>
{% endfor %}
</ul>

</div>
{% endblock content %}

tei/templates/tei/teidoc_nav.html
{% extends "tei/teidoc_detail.html" %}


{% block content %}

<pb-page endpoint="{{ teidoc.publisher.endpoint }}">
    <pb-document id="document1" path="{{ teidoc.path }}" odd="{{ teidoc.odd }}"></pb-document>

    <pb-progress></pb-progress>
    <!-- Output the document title -->
    <pb-view src="document1" xpath="//teiHeader/fileDesc/titleStmt/title">
        <pb-param name="header" value="short" />
    </pb-view>
    <pb-view id="view1" src="document1" view="page" append-footnotes animation column-separator=".tei-cb"></pb-view>
    <footer>
        <!-- Navigate to next page -->
        <pb-navigation direction="forward" keyboard="right">
            <paper-button>
                <iron-icon icon="icons:chevron-right"></iron-icon>
            </paper-button>
        </pb-navigation>
        <!-- Navigate to previous page -->
        <pb-navigation direction="backward" keyboard="left">
            <paper-button>
                <iron-icon icon="icons:chevron-left"></iron-icon>
            </paper-button>
        </pb-navigation>
    </footer>
</pb-page>

{% endblock content %}

tei/templates/tei/teidoc_plugin.html
{% load sekizai_tags %}

<div class="d-flex justify-content-end p-3">
    <a href='{{ instance.doc.url_pdf }}' class="btn btn-outline-primary" ><i class="fas fa-file-pdf fa-sm"></i> PDF</a>
    <a href='{{ instance.doc.url_epub }}' class="btn btn-outline-primary" ><i class="fas fa-book"></i> EPUB</a>
    <a href='{{ instance.doc.url_html }}' class="btn btn-outline-primary" ><i class="fas fa-file-code"></i> HTML</a>
</div>

<pb-page endpoint="{{ instance.doc.publisher.endpoint }}" class="clearfix">
    <pb-document id="document{{ instance.doc.id }}" path="{{ instance.doc.path }}" odd="{{ instance.doc.odd }}" view="page"></pb-document>

    <main>
        <pb-view id="view{{ instance.doc.id }}" src="document{{ instance.doc.id }}" view="page" xpath="//text[@type='source']" style='padding: 15px; margin: 40px;' append-footnotes>
        </pb-view>
        {% if instance.doc.iiif %}
        <pb-facsimile base-uri="{{ instance.doc.iiif.uri }}" default-zoom-level="0" show-navigator="show-navigator" show-navigation-control="show-navigation-control">
        </pb-facsimile>
        {% endif %}
        <!-- Navigate to previous page -->
        <pb-navigation direction="backward" keyboard="left">
            <paper-button>
                <iron-icon icon="icons:chevron-left"></iron-icon>
            </paper-button>
        </pb-navigation>
        <!-- Navigate to next page -->
        <pb-navigation direction="forward" keyboard="right">
            <paper-button>
                <iron-icon icon="icons:chevron-right"></iron-icon>
            </paper-button>
        </pb-navigation>

    </main>

</pb-page>


{% addtoblock "js" %}
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.4.3/webcomponents-loader.js"></script>
<script type="module" src="https://unpkg.com/@teipublisher/pb-components@latest/dist/pb-components-bundle.js"></script>
{% endaddtoblock %}

{% addtoblock "css" %}
<style>
    main {
        display: flex;
        flex-direction: row;
        justify-content: flex-start;
    }
    
    
    pb-navigation[disabled] {
        display: block;
        visibility: hidden;
    }
    
    pb-navigation[direction="forward"] {
        float: right;
    }
    
    #view{{ instance.doc.id }} {
        flex: 3;
        margin-left: 20px;
        font-size: 20px;
        line-height: 1.42857143;
    }
    
    {% if instance.doc.iiif %}
    pb-facsimile {
        flex: 2;
        max-width: 50vw;
        --pb-facsimile-height: 500px;
        margin-right: 20px;
    }
    {% endif %}
    
</style>
{% endaddtoblock %}

tei/templates/tei/teidoc_toggle.html
{% extends "tei/teidoc_detail.html" %}

{% block content %}
<pb-page endpoint="{{ teidoc.publisher.endpoint }}">
    <pb-document id="document2" path="{{ teidoc.path }}" odd="{{ teidoc.odd }}"></pb-document>
    <div class="toolbar">
        <pb-toggle-feature name="highlight2" selector=".tei-foreign,pb-highlight,pb-popover" action="disable" default="off" emit="ex2" subscribe="ex2">Plain Reading View</pb-toggle-feature>
        <pb-toggle-feature name="norm2" selector=".choice,.choice-alternate,br" emit="ex2" subscribe="ex2">
            Normalized View</pb-toggle-feature>
        <!-- Navigate to previous page -->
        <pb-navigation direction="backward" keyboard="left" emit="ex2" subscribe="ex2">
            <paper-icon-button icon="icons:chevron-left"></paper-icon-button>
        </pb-navigation>
        <!-- Navigate to next page -->
        <pb-navigation direction="forward" keyboard="right" emit="ex2" subscribe="ex2">
            <paper-icon-button icon="icons:chevron-right"></paper-icon-button>
        </pb-navigation>
    </div>
    <main>
        <pb-view id="view2" src="document2" xpath="//text[@type='source']" emit="ex2" subscribe="ex2">
        </pb-view>
    </main>
</pb-page>
{% endblock content %}

{% block teihead %}
<style>
body {
    --paper-fab-background: #35424b;
}

main {
    display: flex;
    justify-content: space-between;
}

.toolbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px;
    background-color: #e0e0e0;
}

pb-toggle-feature {
    display: block;
}
</style>
{% endblock teihead %}